package pt.gov.chavemoveldigital.enums;

public enum Municipality {
    AGUEDA("Agueda"),
    ALBERGARIA_A_VELHA("Albergaria A Velha"),
    ANADIA("Anadia"),
    AROUCA("Arouca"),
    AVEIRO("Aveiro"),
    CASTELO_DE_PAIVA("Castelo De Paiva"),
    ESPINHO("Espinho"),
    ESTARREJA("Estarreja"),
    ILHAVO("Ilhavo"),
    MEALHADA("Mealhada"),
    MURTOSA("Murtosa"),
    OLIVEIRA_DE_AZEMEIS("Oliveira De Azemeis"),
    OLIVEIRA_DO_BAIRRO("Oliveira Do Bairro"),
    OVAR("Ovar"),
    SANTA_MARIA_DA_FEIRA("Santa Maria Da Feira"),
    SAO_JOAO_DA_MADEIRA("Sao Joao Da Madeira"),
    SEVER_DO_VOUGA("Sever Do Vouga"),
    VAGOS("Vagos"),
    VALE_DE_CAMBRA("Vale De Cambra"),
    ALJUSTREL("Aljustrel"),
    ALMODOVAR("Almodovar"),
    ALVITO("Alvito"),
    BARRANCOS("Barrancos"),
    BEJA("Beja"),
    CASTRO_VERDE("Castro Verde"),
    CUBA("Cuba"),
    FERREIRA_DO_ALENTEJO("Ferreira Do Alentejo"),
    MERTOLA("Mertola"),
    MOURA("Moura"),
    ODEMIRA("Odemira"),
    OURIQUE("Ourique"),
    SERPA("Serpa"),
    VIDIGUEIRA("Vidigueira"),
    AMARES("Amares"),
    BARCELOS("Barcelos"),
    BRAGA("Braga"),
    CABECEIRAS_DE_BASTO("Cabeceiras De Basto"),
    CELORICO_DE_BASTO("Celorico De Basto"),
    ESPOSENDE("Esposende"),
    FAFE("Fafe"),
    GUIMARAES("Guimaraes"),
    POVOA_DE_LANHOSO("Povoa De Lanhoso"),
    TERRAS_DE_BOURO("Terras De Bouro"),
    VIEIRA_DO_MINHO("Vieira Do Minho"),
    VILA_NOVA_DE_FAMALICAO("Vila Nova De Famalicao"),
    VILA_VERDE("Vila Verde"),
    VIZELA("Vizela"),
    ALFANDEGA_DA_FE("Alfandega Da Fe"),
    BRAGANCA("Braganca"),
    CARRAZEDA_DE_ANSIAES("Carrazeda De Ansiaes"),
    FREIXO_DE_ESPADA_A_CINTA("Freixo De Espada A Cinta"),
    MACEDO_DE_CAVALEIROS("Macedo De Cavaleiros"),
    MIRANDA_DO_DOURO("Miranda Do Douro"),
    MIRANDELA("Mirandela"),
    MOGADOURO("Mogadouro"),
    TORRE_DE_MONCORVO("Torre De Moncorvo"),
    VILA_FLOR("Vila Flor"),
    VIMIOSO("Vimioso"),
    VINHAIS("Vinhais"),
    BELMONTE("Belmonte"),
    CASTELO_BRANCO("Castelo Branco"),
    COVILHA("Covilha"),
    FUNDAO("Fundao"),
    IDANHA_A_NOVA("Idanha A Nova"),
    OLEIROS("Oleiros"),
    PENAMACOR("Penamacor"),
    PROENCA_A_NOVA("Proenca A Nova"),
    SERTA("Serta"),
    VILA_DE_REI("Vila De Rei"),
    VILA_VELHA_DE_RODAO("Vila Velha De Rodao"),
    ARGANIL("Arganil"),
    CANTANHEDE("Cantanhede"),
    COIMBRA("Coimbra"),
    CONDEIXA_A_NOVA("Condeixa A Nova"),
    FIGUEIRA_DA_FOZ("Figueira Da Foz"),
    GOIS("Gois"),
    LOUSADA("Lousada"),
    LOUSAA("Lousaa"),
    MIRA("Mira"),
    MIRANDA_DO_CORVO("Miranda Do Corvo"),
    MONTEMOR_O_VELHO("Montemor O Velho"),
    OLIVEIRA_DO_HOSPITAL("Oliveira Do Hospital"),
    PAMPILHOSA_DA_SERRA("Pampilhosa Da Serra"),
    PENACOVA("Penacova"),
    PENELA("Penela"),
    SOURE("Soure"),
    TABUA("Tabua"),
    ALANDROAL("Alandroal"),
    ARRAIOLOS("Arraios"),
    BORBA("Borba"),
    ESTREMOZ("Estremoz"),
    EVORA("Evora"),
    MONTEMOR_O_NOVO("Montemor O Novo"),
    MORA("Mora"),
    MOURAO("Mourao"),
    PORTEL("Portel"),
    REDONDO("Redondo"),
    REGUENGOS_DE_MONSARAZ("Reguengos De Monsaraz"),
    VENDAS_NOVAS("Vendas Novas"),
    VIANA_DO_ALENTEJO("Viana Do Alentejo"),
    VILA_VICOSA("Vila Vicosa"),
    ALBUFEIRA("Albufeira"),
    ALCOUTIM("Alcoutim"),
    ALJEZUR("Aljezur"),
    CASTRO_MARIM("Castro Marim"),
    FARO("Faro"),
    LAGOA("Lagoa"),
    LAGOS("Lagos"),
    LOULE("Loule"),
    MONCHIQUE("Monchique"),
    OLHAO("Olhao"),
    PORTIMAO("Portimao"),
    SAO_BRAS_DE_ALPORTEL("Sao Bras De Alportel"),
    SILVES("Silves"),
    TAVIRA("Tavira"),
    VILA_DO_BISPO("Vila Do Bispo"),
    VILA_REAL_DE_SANTO_ANTONIO("Vila Real De Santo Antonio"),
    AGUIAR_DA_BEIRA("Aguiar Da Beira"),
    ALMEIDA("Almeida"),
    CELORICO_DA_BEIRA("Celorico Da Beira"),
    FIGUEIRA_DE_CASTELO_RODRIGO("Figueira De Castelo Rodrigo"),
    FORNOS_DE_ALGODRES("Fornos De Algodres"),
    GOUVEIA("Gouveia"),
    GUARDA("Guarda"),
    MANTEIGAS("Manteigas"),
    MEDA("Meda"),
    PINHEL("Pinhel"),
    SABUGAL("Sabugal"),
    SEIA("Seia"),
    TRANCOSO("Trancoso"),
    VILA_NOVA_DE_FOZ_COA("Vila Nova De Foz Coa"),
    ALCOBACA("Alcobaca"),
    ALVAIAZERE("Alvaiazere"),
    ANSIAO("Ansiao"),
    BATALHA("Batalha"),
    BOMBARRAL("Bombarral"),
    CALDAS_DA_RAINHA("Caldas Da Rainha"),
    CASTANHEIRA_DE_PERA("Castanheira De Pera"),
    FIGUEIRO_DOS_VINHOS("Figueiro Dos Vinhos"),
    LEIRIA("Leiria"),
    MARINHA_GRANDE("Marinha Grande"),
    NAZARE("Nazare"),
    OBIDOS("Obidos"),
    OUREM("Ourém"),
    PEDROGAO_GRANDE("Pedrogao Grande"),
    PENICHE("Peniche"),
    POMBAL("Pombal"),
    PORTO_DE_MOS("Porto De Mos"),
    ALENQUER("Alenquer"),
    AMADORA("Amadora"),
    ARRUDA_DOS_VINHOS("Arruda Dos Vinhos"),
    AZAMBUJA("Azambuja"),
    CADAVAL("Cadaval"),
    CASCAIS("Cascais"),
    LISBOA("Lisboa"),
    LOURES("Loures"),
    LOURINHA("Lourinha"),
    MAFRA("Mafra"),
    ODIVELAS("Odivelas"),
    OEIRAS("Oeiras"),
    SINTRA("Sintra"),
    SOBRAL_DE_MONTE_AGRACO("Sobral De Monte Agraco"),
    TORRES_VEDRAS("Torres Vedras"),
    VILA_FRANCA_DE_XIRA("Vila Franca De Xira"),
    ALTER_DO_CHAO("Alter Do Chao"),
    ARRONCHES("Arronches"),
    AVIS("Avis"),
    CAMPO_MAIOR("Campo Maior"),
    CASTELO_DE_VIDE("Castelo De Vide"),
    CRATO("Crato"),
    ELVAS("Elvas"),
    FRONTEIRA("Fronteira"),
    GAVIAO("Gaviao"),
    MARVAO("Marvao"),
    MONFORTE("Monforte"),
    NISA("Nisa"),
    PONTE_DE_SOR("Ponte De Sor"),
    PORTALEGRE("Portalegre"),
    SOUSEL("Sousel"),
    AMARANTE("Amarante"),
    BAIAO("Baiao"),
    FELGUEIRAS("Felgueiras"),
    GONDOMAR("Gondomar"),
    LOUSADA_PORTO("Lousada Porto"),
    MAIA("Maia"),
    MARCO_DE_CANAVESES("Marco De Canaveses"),
    MATOSINHOS("Matosinhos"),
    PACOS_DE_FERREIRA("Pacos De Ferreira"),
    PAREDES("Paredes"),
    PENAFIEL("Penafiel"),
    PORTO("Porto"),
    POVOA_DE_VARZIM("Povoa De Varzim"),
    RIO_MAIOR("Rio Maior"),
    SANTO_TIRSO("Santo Tirso"),
    TROFA("Trofa"),
    VALONGO("Valongo"),
    VILA_DO_CONDE("Vila Do Conde"),
    ABRANTES("Abrantes"),
    ALCANENA("Alcanena"),
    ALMEIRIM("Almeirim"),
    ALPIARCA("Alpiarca"),
    BENAVENTE("Benavente"),
    CARTAXO("Cartaxo"),
    CHAMUSCA("Chamusca"),
    CONSTANCIA("Constancia"),
    CORUCHE("Coruche"),
    ENTRONCAMENTO("Entroncamento"),
    FERREIRA_DO_ZEZERE("Ferreira Do Zezere"),
    GOLEGA("Golega"),
    MACAO("Macao"),
    RIO_MAIOR_SANTAREM("Rio Maior Santarem"),
    SALVATERRA_DE_MAGOS("Salvaterra De Magos"),
    SANTAREM("Santarem"),
    SARDOAL("Sardoal"),
    TOMAR("Tomar"),
    TORRES_NOVAS("Torres Novas"),
    VILA_NOVA_DA_BARQUINHA("Vila Nova Da Barquinho"),
    ALCACER_DO_SAL("Alcacer Do Sal"),
    ALCOCHETE("Alcochete"),
    ALMADA("Almada"),
    BARREIRO("Barreiro"),
    GRANDOLA("Grandola"),
    MOITA("Moita"),
    MONTIJO("Montijo"),
    PALMELA("Palmela"),
    SANTIAGO_DO_CACEM("Santiago Do Cacem"),
    SEIXAL("Seixal"),
    SESIMBRA("Sesimbra"),
    SETUBAL("Setubal"),
    SINES("Sines"),
    ARCOS_DE_VALDEVEZ("Arcos De Valdevez"),
    CAMINHA("Caminha"),
    MELGACO("Melgaco"),
    MONCAO("Moncao"),
    PAREDES_DE_COURA("Paredes De Coura"),
    PONTE_DA_BARCA("Ponte Da Barca"),
    PONTE_DE_LIMA("Ponte De Lima"),
    VALENCA("Valenca"),
    VIANA_DO_CASTELO("Viana Do Castelo"),
    VILA_NOVA_DE_CERVEIRA("Vila Nova De Cerveira"),
    ALIJO("Alijo"),
    BOTICAS("Boticas"),
    CHAVES("Chaves"),
    MESAO_FRIO("Mesao Frio"),
    MONDIM_DE_BASTO("Mondim De Basto"),
    MONTALEGRE("Montalegre"),
    MURCA("Murca"),
    PESO_DA_REGUA("Peso Da Regua"),
    RIBEIRA_DE_PENA("Ribeira De Pena"),
    SABROSA("Sabrosa"),
    SANTA_MARTA_DE_PENAGUIAO("Santa Marta De Penaguiao"),
    VALPACOS("Valpacos"),
    VILA_POUCA_DE_AGUIAR("Vila Pouca De Aguiar"),
    VILA_REAL("Vila Real"),
    ARMAMAR("Armamar"),
    CARREGAL_DO_SAL("Carregal Do Sal"),
    CASTRO_DAIRE("Castro Daire"),
    CINFAES("Cinfaes"),
    LAMEGO("Lamego"),
    MANGUALDE("Mangualde"),
    MOIMENTA_DA_BEIRA("Moimenta Da Beira"),
    MORTAGUA("Mortagua"),
    NELAS("Nelas"),
    OLIVEIRA_DE_FRADES("Oliveira De Frades"),
    PENALVA_DO_CASTELO("Penalva Do Castelo"),
    PENEDONO("Penedono"),
    RESENDE("Resende"),
    SANTA_COMBA_DAO("Santa Comba Dao"),
    SAO_JOAO_DA_PESQUEIRA("Sao Joao Da Pesqueira"),
    SAO_PEDRO_DO_SUL("Sao Pedro Do Sul"),
    SATAO("Satao"),
    SERNANCELHE("Sernancelhe"),
    TABUACO("Tabuaco"),
    TAROUCA("Tarouca"),
    TONDELA("Tondela"),
    VILA_NOVA_DE_PAIVA("Vila Nova De Paiva"),
    VISEU("Viseu"),
    VOUZELA("Vouzela"),
    ANGRA_DO_HEROISMO("Angra Do Heroismo"),
    CALHETA_AZORES("Calheta Azores"),
    CORVO("Corvo"),
    HORTA("Horta"),
    LAGOA_AZORES("Lagoa Azores"),
    LAJES_DAS_FLORES("Lajes Das Flores"),
    LAJES_DO_PICO("Lajes Do Pico"),
    MADALENA("Madalena"),
    NORDESTE("Nordeste"),
    POVOACAO("Povoacao"),
    PRAIA_DA_VITORIA("Praia Da Vitoria"),
    RIBEIRA_GRANDE("Ribeira Grande"),
    SANTA_CRUZ_DA_GRACIOSA("Santa Cruz Da Graciosa"),
    SANTA_CRUZ_DAS_FLORES("Santa Cruz Das Flores"),
    SAO_ROQUE_DO_PICO("Sao Roque Do Pico"),
    VELAS("Velas"),
    VILA_DO_PORTO("Vila Do Porto"),
    VILA_FRANCA_DO_CAMPO("Vila Franca Do Campo"),
    CALHETA_MADEIRA("Calheta Madeira"),
    CAMARA_DE_LOBOS("Camara De Lobos"),
    FUNCHAL("Funchal"),
    MACHICO("Machico"),
    PONTA_DO_SOL("Ponta Do Sol"),
    PORTO_MONIZ("Porto Moniz"),
    PORTO_SANTO("Porto Santo"),
    RIBEIRA_BRAVA("Ribeira Brava"),
    SANTA_CRUZ_MADEIRA("Santa Cruz Madeira"),
    SANTANA("Santana"),
    SAO_VICENTE("Sao Vicente");

    private final String value;

    Municipality(String value) {
        this.value = value;
    }

    public String getValue() {
        return value;
    }
}